# Generated by Django 4.2.4 on 2023-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_game_rating_game_age_rating_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
