# Generated by Django 4.2.4 on 2023-09-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_usertvshow_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertvshow',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
