# Generated by Django 4.2.4 on 2023-09-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_delete_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
