# Generated by Django 4.2.4 on 2023-09-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
